- name: breaking
  description: Breaking Changes
  color: 7c3ea5
- name: bug
  description: Something isn't working
  color: d73a4a
- name: build
  description: Changes that affect the build system or external dependencies
  color: fc964e
- name: ci
  description: Changes to CI configuration files and scripts
  color: 00485e
- name: dependencies
  description: Dependencies
  color: 00ce44
- name: documentation
  description: Improvements or additions to documentation
  color: 0075ca
- name: feature
  description: New feature or request
  color: a2eeef
- name: performance
  description: A code change that improves performance
  color: f3ffb2
- name: question
  description: Further information is requested
  color: d876e3
- name: refactoring
  description: A code change that neither fixes a bug nor adds a feature
  color: d4c5f9
- name: removal
  description: Removals and Deprecations
  color: f00000
- name: style
  description: Changes that do not affect the meaning of the code
  color: ffc6df
- name: testing
  description: Adding missing tests or correcting existing tests
  color: 79e57f
- name: "skip-changelog"
  description: Changes that should be omitted from the release notes
  color: ededed
- name: "release"
  description: Release a new version of the code
  color: ed67ed
- name: cookiecutter
  description: Changes outside of the template directory
  color: f9ffb2
