version-template: "v$MAJOR.$MINOR.$PATCH"
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'bug'
  default: patch
name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: ":boom: Breaking Changes"
    label: "breaking"
  - title: ":rocket: Features"
    label: "feature"
  - title: ":fire: Removals and Deprecations"
    label: "removal"
  - title: ":beetle: Fixes"
    label: "bug"
  - title: ":racehorse: Performance"
    label: "performance"
  - title: ":rotating_light: Testing"
    label: "testing"
  - title: ":construction_worker: Continuous Integration"
    label: "ci"
  - title: ":books: Documentation"
    label: "documentation"
  - title: ":hammer: Refactoring"
    label: "refactoring"
  - title: ":lipstick: Style"
    label: "style"
  - title: ":package: Dependencies"
    labels:
      - "dependencies"
      - "build"
autolabeler:
  - label: 'breaking'
    branch:
      - '/breaking\/.+/'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
  - label: 'removal'
    branch:
      - '/removal\/.+/'
  - label: 'bug'
    branch:
      - '/bug\/.+/'
      - '/fix\/.+/'
  - label: 'performance'
    branch:
      - '/performance\/.+/'
  - label: 'testing'
    branch:
      - '/testing\/.+/'
  - label: 'ci'
    branch:
      - '/ci\/.+/'
  - label: 'documentation'
    branch:
      - '/documentation\/.+/'
  - label: 'refactoring'
    branch:
      - '/refactoring\/.+/'
  - label: 'style'
    branch:
      - '/style\/.+/'
  - label: 'dependencies'
    branch:
      - '/dependencies\/.+/'
  - label: 'build'
    branch:
      - '/build\/.+/'
  - label: 'release'
    branch:
      - '/release\/.+/'
exclude-labels:
  - "skip-changelog"
  - "release"
