repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-ast
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: make flake8
        language: system
      - id: mypy
        name: mypy
        entry: make mypy
        language: system
      - id: pydocstyle
        name: pydocstyle
        entry: make pydocstyle
        language: system
      - id: isort
        name: isort
        entry: make isort
        language: system
      - id: black
        name: black
        entry: make black
        language: system
      - id: safety
        name: safety
        entry: make safety
        language: system
      - id: bandit
        name: bandit
        entry: make bandit
        language: system
