name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python ${{ '{{' }} matrix.python-version {{ '}}' }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
        architecture: x64

    - name: Install Poetry
      uses: snok/install-poetry@v1.3.1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Cache Environment
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ '{{' }} runner.os {{ '}}' }}-${{ '{{' }} steps.setup-python.outputs.python-version {{ '}}' }}-${{ '{{' }} hashFiles('**/poetry.lock') {{ '}}' }}

    - name: Configure Environment on Cache Miss
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: make init

    - name: Run Linting and Formatting
      run: make pre-commit

    - name: Run Tests
      run: make test
