name: Deploy Docs

on:
  push:
    branches: [ main ]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        architecture: x64

    - name: Install Material for MKDocs
      run: pip install mkdocs-material

    - name: Deploy Docs
    - run: mkdocs gh-deploy --force
