name: Labeler

on:
  push:
    branches: [ main ]

jobs:
  labeler:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labeler.yml
          skip-delete: false
          dry-run: false
