name: Release Drafter

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  draft_release:

    runs-on: ubuntu-latest

    steps:
      - name: Draft Release
        uses: release-drafter/release-drafter@v5.15.0
        with:
          config-name: release-drafter.yml
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN }}
